export const MY_ROUTE = {
  LANDING: "/",
  CREATE_WALLET: "/create",
  ACCESS_WALLET: "/access",
  DASHBOARD: "/dashboard",
};

export const LANDING_ROUTE = MY_ROUTE.LANDING;
export const CREATE_WALLET_ROUTE = MY_ROUTE.CREATE_WALLET;
export const ACCESS_WALLET_ROUTE = MY_ROUTE.ACCESS_WALLET;
export const DASHBOARD_ROUTE = MY_ROUTE.DASHBOARD;
